[project]
name = "receipe-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=2.3.0",
    "huggingface-hub>=1.22.0",
    "pinecone>=9.1.0",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.6.0",
]
